In [ ]:
import torch
import numpy as np

In [ ]:
a = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
b = [[1., 2., 3.],
     [4., 5., 6.],
     [7., 8., 9.]]

In [ ]:
# Create tensors
t = torch.tensor(a)
u = torch.tensor(b)
print(type(t))
print(t.shape)
print(type(u))
print(u.shape)

In [ ]:
# Torch attributes
print(t.dtype)
print(t.device)
print(t.layout)
print(u.dtype)
print(u.device)
print(u.layout)
print(torch.device('cuda:0'))

In [ ]:
# Create tensor without data
print(torch.eye(2))
print(torch.zeros(4,3))
print(torch.ones(2,3))
print(torch.rand(2,2))

In [ ]:
data = np.array([1,2,3])

t1 = torch.Tensor(data)     # Deep copy, static type
t2 = torch.tensor(data)     # Deep copy, type similar to 'data'
t3 = torch.as_tensor(data)  # Shared data, any array
t4 = torch.from_numpy(data) # Shared data, only numpy array

In [ ]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)
print(torch.tensor(data, dtype=torch.float64))

In [ ]:
data[0] = 5
data[1] = -1

In [ ]:
print(data)
print(t1)
print(t2)
print(t3)
print(t4)

In [ ]:
t = torch.tensor([
        [1,1,1,1],
        [2,2,2,2],
        [3,3,3,3]
    ], dtype=torch.float32)

In [ ]:
# Reshape
print(t.shape)
print(t.numel())
print(t.reshape(1,12))
print(t.reshape(-1))                              # auto calculating the length
print(t.reshape(1,-1))                            # auto calculating the length
print(t.reshape(4,3))
print(t.reshape(2,2,3))
print(t.reshape(1,12).squeeze())                  # remove all dimension of size 1
print(t.reshape(1,12).squeeze().unsqueeze(dim=0)) # wrap the given dimension with an array
print(t.reshape(1,12).squeeze().unsqueeze(dim=1)) # wrap the given dimension with an array

In [ ]:
# Concatenation
t1 = torch.tensor([[1,2],
                   [3,4]])
t2 = torch.tensor([[5,6],
                   [7,8]])

print(torch.cat((t1, t2), dim=0))
print(torch.cat((t1, t2), dim=1))

In [90]:
# Stack tensors
t1 = torch.tensor([[1,1,1,1],
                   [1,1,1,1],
                   [1,1,1,1],
                   [1,1,1,1]])
t2 = torch.tensor([[2,2,2,2],
                   [2,2,2,2],
                   [2,2,2,2],
                   [2,2,2,2]])
t3 = torch.tensor([[3,3,3,3],
                   [3,3,3,3],
                   [3,3,3,3],
                   [3,3,3,3]])
t = torch.stack((t1, t2, t2))
print(t.shape) # Need to add a color channel
t = t.reshape(3, 1, 4, 4)
print(t.shape)
print(t[0])
print(t[0][0])
print(t[0][0][0])
print(t[0][0][0][0])

torch.Size([3, 4, 4])
torch.Size([3, 1, 4, 4])
tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
tensor([1, 1, 1, 1])
tensor(1)


In [98]:
# Flatten an image
print(torch.flatten(t, start_dim=1))    # flatten start from dim 1
print(t.reshape((t.shape[0],t.shape[2] * t.shape[3])))
print(torch.flatten(t, start_dim=1).shape)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])
torch.Size([3, 16])
